version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user
    description: /home/ec2-user
file_exists_behavior: OVERWRITE
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user 
    
hooks:
#   BeforeInstall:
#     - location: scripts/release/before_install.sh
#       runas: ec2-user
  AfterInstall:
    - location: scripts/after_install.sh
      runas: ec2-user